services:
  - type: web
    name: cv-roaster-api
    runtime: python            # <- N O M A R C A R versión aquí
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"      # <- versión fully-qualified. Podés usar "3.10.12" si preferís 3.10
